---
AllCops:
  TargetRubyVersion: 2.7
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: no
Layout/DefEndAlignment:
  AutoCorrect: yes
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: yes
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/LineLength:
  Max: 120
Lint/AmbiguousBlockAssociation:
  Exclude:
    - test/**/*  
Lint/MixedRegexpCaptureTypes:
  Enabled: yes
Layout/SpaceAroundMethodCallOperator:
  Enabled: yes
Lint/DeprecatedOpenSSLConstant:
  Enabled: yes
Lint/RaiseException:
  Enabled: yes
Lint/StructNewOverride:
  Enabled: yes
Lint/UnusedMethodArgument:
  Enabled: no
Lint/Void:
  Exclude:
    - test/**/*
    - generated/**/*
    - embedded/**/*
Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
Style/CommandLiteral:
  EnforcedStyle: percent_x
Style/ExponentialNotation:
  Enabled: yes
  EnforcedStyle: engineering
Style/FrozenStringLiteralComment:
  EnforcedStyle: always_true
Style/GuardClause:
  Enabled: no
Style/HashEachMethods:
  Enabled: yes
Style/HashTransformKeys:
  Enabled: yes
Style/HashTransformValues:
  Enabled: yes
Style/KeywordParametersOrder:
  Enabled: no
Style/MultilineBlockChain:
  Enabled: no
Style/Next:
  Enabled: no
Style/RedundantRegexpCharacterClass:
  Enabled: yes
Style/RedundantRegexpEscape:
  Enabled: yes
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/Semicolon:
  Exclude:
    - test/**/*
Style/SlicingWithRange:
  Enabled: yes
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  